// Copyright (C) WithLithum & IceCraft contributors 2024.
// Licensed under GNU General Public License, version 3 or (at your opinion)
// any later version. See COPYING in repository root.

namespace IceCraft.Tests;

using System.Text;
using IceCraft.Api.Platform;
using IceCraft.Core.Platform;
using IceCraft.Tests.Helpers;

public class ExecutionScriptTests
{
    private static readonly ExecutableRegistrationEntry DummyEntryNoArgs = new()
    {
        LinkTarget = "test",
        PackageRef = "test"
    };

    [LinuxFact]
    public async Task Posix_NoArgs()
    {
        const string FilePath = "/icMock/packages/test/test";

        // Arrange
        var generator = new PosixExecutionScriptGenerator();

        // Act
        var stream = new MemoryStream();
        await generator.WriteExecutionScriptAsync(DummyEntryNoArgs, FilePath, stream);
        stream.Close();

        // Assert
        var array = stream.ToArray();
        System.Console.WriteLine(array.Length);
        var str = Encoding.UTF8.GetString(stream.ToArray());
        Assert.Equal($"""
        #!/bin/sh
        # Generated by IceCraft
        '{FilePath}' $@
        
        """.Replace("\r\n", "\n"), str);
    }
}
