#!/bin/sh

# IceCraft prepped script installer.

# Basic variables
SCRNAME=$(basename "$0")
NEWLINE='\n'
SH_OPTSTRING="t:h"

TARGET_PATH="$HOME/.local/share/IceCraft"

# Check if an environment variable called XDG_DATA_HOME is set
if [ -n "$XDG_DATA_HOME" ]; then
    # if set use the data home path
    TARGET_PATH="$XDG_DATA_HOME/IceCraft"
fi

printmsg() {
    echo "$SCRNAME: $1"
}

is_user_root () { [ "$(id -u)" -eq 0 ]; }

if is_user_root; then
    printmsg "error: the $SCRNAME script is intended only for per-user"
    printmsg "installation. It will not work for root."
    echo ""
    printmsg "if you want to install for root, conduct a manual install."
    exit 1
fi

while getopts $SH_OPTSTRING flag; do
    if [ "$flag" = '?' ]; then
        exit 1
    fi

    if [ "$flag" = 'h' ]; then
        echo "usage: $SCRNAME [-t <install_location>] [-h]"
        echo ""
        echo "-t: The location to install to"
        echo "-h: Shows this help message and exit"
        exit 0
    fi

    if [ "$flag" = 't' ]; then
        TARGET_PATH=$OPTARG
    fi
done

# Test for prepped_ic file (must run in extracted archive)
if [ ! -e ".prepped_ic" ]; then
    printmsg "Please run this script under an IceCraft installation archive."
    exit 1
fi

# Print intro

echo "  _____          _____            __ _   "
echo "|_   _|        / ____|          / _| | "
echo "   | |  ___ ___| |     _ __ __ _| |_| |_ "
echo "   | | / __/ _ \ |    | '__/ _| |  _| __| "
echo "  _| || (_|  __/ |____| | | (_| | | | |_ "
echo " |_____\___\___|\_____|_|  \__,_|_|  \__|"
echo "                                         "

echo "-----------------------------------------"
echo ""

echo "Welcome to IceCraft Installer!"
echo ""
echo "This script will install IceCraft for you."
echo "Please note that while .NET is not required for installing, you need"
echo "at least .NET Runtime 8 to run IceCraft."
echo ""
echo "IceCraft will be installed at '$TARGET_PATH'."
echo "If you are ready to continue, press Y. If not, press N to exit."
echo ""

# Test for Y/N

read yn
case $yn in
    "yes" ) ;;
    "no" ) exit;;
    * ) echo "Invalid response, assuming no";
        exit 1;;
esac

write_run_script() {
    touch $1

    echo "#!/bin/sh" | tee "$1"
    echo "# Generated by IceCraft installer" | tee -a "$1"
    echo "$TARGET_PATH/packages/icecraft/unitary/IceCraft \$@" | tee -a "$1"

    echo ""
    echo "(please ignore the above script)"
    echo "-----------------------------------------"
}

# Copy files
mkdir -p "$TARGET_PATH/packages"
cp -p -r -t "$TARGET_PATH/packages" $PWD/**/*

IC_SCRIPT_PATH="$TARGET_PATH/run/IceCraft"
mkdir -p "$TARGET_PATH/run"

# Write script, set permissions
write_run_script "$IC_SCRIPT_PATH"
chmod +x "$IC_SCRIPT_PATH"

echo "CONGRATULATIONS!"
echo ""
echo "IceCraft have been installed!"
echo "It is recommended that you run the following command:"
echo "\"$IC_SCRIPT_PATH init\""
echo "then restart your terminal!"
