#!/bin/sh

# IceCraft prepped script installer.

# Basic variables
SCRNAME=$(basename "$0")
NEWLINE='\n'

printmsg() {
    echo "$SCRNAME: $1"
}

is_user_root () { [ "$(id -u)" -eq 0 ]; }

if is_user_root; then
    printmsg "error: the $SCRNAME script is intended only for per-user"
    printmsg "installation. It will not work for root."
    echo ""
    printmsg "if you want to install for root, conduct a manual install."
    exit 1
fi

# Test for src folder (must run in repo root)
if [ ! -e ".prepped_ic" ]; then
    printmsg "probably not IceCraft dev directory ('src' doesn't exist)"
    printmsg "if you are in scripts directory, move upwards"
    printmsg "then call 'scripts/install.sh'"
    exit 1
fi

write_run_script() {
    touch $1

    echo "#!/bin/sh" | tee "$1"
    echo "# Generated by IceCraft installer" | tee -a "$1"
    echo "$PWD/run/prep/packages/icecraft/unitary/IceCraft \$@" | tee -a "$1"
}

write_run_script "$PWD/bin/prep/test.sh"
