# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  IC_PROJECT_SLN: "src/IceCraft.sln"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.IC_PROJECT_SLN }}
    - name: Build
      run: dotnet build ${{ env.IC_PROJECT_SLN }} --no-restore
    - name: Test
      run: dotnet test ${{ env.IC_PROJECT_SLN }} --no-build --verbosity normal
