namespace IceCraft.Core.Platform;

using System.IO;
using System.Threading.Tasks;
using IceCraft.Api.Platform;
using IceCraft.Core.Installation.Execution;

public class PosixExecutionScriptGenerator : IExecutionScriptGenerator
{
    public async Task WriteExecutionScriptAsync(ExecutableRegistrationEntry entry, string executablePath, Stream stream)
    {
        var writer = new StreamWriter(stream);
        await writer.WriteLineAsync("#!/bin/sh");
        await writer.WriteLineAsync("# Generated by IceCraft");
        
        if (entry.EnvironmentVariables != null)
        {
            foreach (var variable in entry.EnvironmentVariables)
            {
                await writer.WriteLineAsync($"export {variable.Key}='{variable.Value.Replace('\'', '"')}'");
            }
        }

        await writer.WriteLineAsync($"'{executablePath}' $@");
        await writer.FlushAsync();
    }
}
