#!/bin/sh

SCRNAME=$(basename "$0")

# Test for src folder (must run in repo root)
if [ ! -d "src" ]; then
    echo "$SCRNAME: probably not IceCraft dev directory ('src' doesn't exist)"
    exit 1
fi

mkdir -p "$PWD/run"
mkdir -p "$PWD/run/bin"

# Configure Icecraft to isolate environment
export ICECRAFT_ROOT="$PWD/run"
export ICECRAFT_DRY_ENV=1

dotnet run --project "$PWD/src/IceCraft/IceCraft.csproj" --no-self-contained -- $@